### ISSUE TITLE
Found 3 read-only properties Published, maybe Public better.

### ISSUE THREAD

**Issue by LivingInFHL** [digao-dalpiaz/HTLabel#2]
Properties seen as below can not be set through Object Inspector. 
But they are seen from Object Inspector. Maybe some changes need to be done.

If they are Public, how nice it will be.

property Lines: Integer read FLines;
property TextWidth: Integer read FTextWidth;
property TextHeight: Integer read FTextHeight;

-- Thank you.

**Comment by digao-dalpiaz** [comment]
Hey @LivingInFHL,

Thank you for verifying the component.

These three properties were made to be really published, so, at design-time, we can see how the values interact with AutoWidth, AutoHeight and MaxWidth properties.

Is only a convenience for the programmer to better understand the component.

**Comment by LivingInFHL** [comment]
Great. OK. 
Thanks a lot.

**Comment by LivingInFHL** [comment]
Time to close this issue.
